# docker-compose to deploy in development mode

version: "3.8"

services:
  db:
    networks:
      - lg-stats
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - 5432:5432
    container_name: lg-stats-db
  front:
    networks:
      - lg-stats
    build:
      context: ../front
      dockerfile: Dockerfile-dev
    volumes: # Enable server reload on code changes
      - ../front:/app
    ports:
      - 3000:3000
    restart: on-failure
    container_name: lg-stats-front
    env_file:
      - ../front/.env.template
  back-end:
    networks:
      - lg-stats
    build:
      context: ../back-end
      dockerfile: Dockerfile-dev
    volumes: # Enable server reload on code changes
      - ../back-end:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ../back-end/.env.template
    restart: on-failure
    container_name: lg-stats-back-end

networks:
  lg-stats:
