/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface SignUp {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
  tl_nickname: string;
}
